on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

